- name: install cart component
  hosts: cart
  become: yes
  tasks:
    - name: install python
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      loop:
      - python36
      - gcc
      - python3-devel

    - name: check roboshop user exist or not
      ansible.builtin.shell: id roboshop
      register: out
      ignore_errors: true

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0

    - name: check directory is already exist or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False


    - name: extract module
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
        dest: /app
        remote_src: yes


    - name: download dependencies
      ansible.builtin.shell: pip3.6 install -r requirements.txt
      args:
          chdir: /app

    - name: copy payment service
      ansible.builtin.copy:
          src: payment.service
          dest: /etc/systemd/system/payment.service

    - name: daemon reload
      ansible.builtin.systemd:
         daemon_reload: true

    - name: restart payment
      ansible.builtin.service:
          name: payment
          state: restarted
          enabled: true