- name: installing redis
  hosts: redis
  become: yes
  tasks:
    - name: install rpm
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
        state: installed
        disable_gpg_check: true

    - name: enable redis
      ansible.builtin.command: yum module enable redis:remi-6.2 -y


